apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: macina-be
    app.kubernetes.io/managed-by: ArgoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        role: webui
        version: 1.0.0
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        env:
        - name: LOGGING_LEVEL_ROOT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}
              key: LOGGING_LEVEL_ROOT

        - name: DENODO_CLIENT_PASSWORD      #TODO valore definito in external secret
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: DENODO_CLIENT_PASSWORD

        volumeMounts:
          - name: config
            mountPath: /app/config
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}

