apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Release.Name }}-store #TODO deve fare matching col nome di una risorsa Kubernetes di tipo SecretStore

  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner

  data:
    - secretKey: DENODO_CLIENT_PASSWORD    # valore inserito come esempio
      remoteRef:
        key: be-services-denodo-client-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None