spring:
  autoconfigure:
    exclude:
      # DataSource + TransactionManager (nuovo package in Boot 4)
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration
      
      # JPA/Hibernate (nuovo package in Boot 4)
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      
      # (opzionale) Disabilita anche Spring Data JPA repositories se presenti in classpath
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

temporal:
  address: 127.0.0.1:7233
  namespace: default

logging:
  level:
    root: INFO