spring:
  application:
    name: macina-be
  
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

  profiles:
    active: local #worker (se si ha temporal attivato in locale, allora local è da sostituire con worker)

temporal:
  address: 127.0.0.1:7233
  namespace: default

server:
  servlet:
    context-path: /macina-be

logging:
  level:
    root: INFO
    it.credem.macina_be: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  file:
    name: logs/macina-be.log

